In [1]:
import pandas as pd
import numpy as np

In [2]:
# azureml-core of version 1.0.72 or higher is required
# azureml-dataprep[pandas] of version 1.1.34 or higher is required
from azureml.core import Workspace, Dataset

subscription_id = 'caaae8aa-a0a7-44db-a52c-2690c23ed8c4'
resource_group = 'ST2AIC-BD-1-SG1'
workspace_name = 'espace_de_travail_eccher'

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset = Dataset.get_by_name(workspace, name='prj_train_eccher')
df = dataset.to_pandas_dataframe()
df.columns = df.iloc[0]
df = df.drop([0])
df = df.drop(['Id'], axis=1)

In [3]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,2,2008,WD,Normal,208500
2,20,RL,80,9600,Pave,NA,Reg,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,5,2007,WD,Normal,181500
3,60,RL,68,11250,Pave,NA,IR1,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,9,2008,WD,Normal,223500
4,70,RL,60,9550,Pave,NA,IR1,Lvl,AllPub,Corner,...,0,NA,NA,NA,0,2,2006,WD,Abnorml,140000
5,60,RL,84,14260,Pave,NA,IR1,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,12,2008,WD,Normal,250000

In [4]:
df.isnull()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1457,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1458,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1459,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1460,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df = df.replace("NA",np.nan)

In [6]:
for i in df.columns:
    print(i, df[f'{i}'].isna().any())

MSSubClass False
MSZoning False
LotFrontage True
LotArea False
Street False
Alley True
LotShape False
LandContour False
Utilities False
LotConfig False
LandSlope False
Neighborhood False
Condition1 False
Condition2 False
BldgType False
HouseStyle False
OverallQual False
OverallCond False
YearBuilt False
YearRemodAdd False
RoofStyle False
RoofMatl False
Exterior1st False
Exterior2nd False
MasVnrType True
MasVnrArea True
ExterQual False
ExterCond False
Foundation False
BsmtQual True
BsmtCond True
BsmtExposure True
BsmtFinType1 True
BsmtFinSF1 False
BsmtFinType2 True
BsmtFinSF2 False
BsmtUnfSF False
TotalBsmtSF False
Heating False
HeatingQC False
CentralAir False
Electrical True
1stFlrSF False
2ndFlrSF False
LowQualFinSF False
GrLivArea False
BsmtFullBath False
BsmtHalfBath False
FullBath False
HalfBath False
BedroomAbvGr False
KitchenAbvGr False
KitchenQual False
TotRmsAbvGrd False
Functional False
Fireplaces False
FireplaceQu True
GarageType True
GarageYrBlt True
GarageFinish True
GarageCars False
GarageArea False
GarageQual True
GarageCond True
PavedDrive False
WoodDeckSF False
OpenPorchSF False
EnclosedPorch False
3SsnPorch False
ScreenPorch False
PoolArea False
PoolQC True
Fence True
MiscFeature True
MiscVal False
MoSold False
YrSold False
SaleType False
SaleCondition False
SalePrice False

# problematic column with Na value:
        lot frontage replace by 0
        electrical replace by the bigest in number of appearance
        fireplacequ replace by the bigest in number of appearance
        garage seems complicated let's see this after
        pool seems complicated let's see this after

In [20]:
df[df.Electrical.isna()]
df.Electrical = df.Electrical.replace(np.nan, 'SBrkr')
df[df.Electrical.isna()]

Empty DataFrame
Columns: [MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 80 columns]

In [19]:
df[df.LotFrontage.isna()]
df.LotFrontage = df.LotFrontage.replace(np.nan, '0')
df[df.LotFrontage=='0']

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
8,60,RL,0,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
13,20,RL,0,12968,Pave,NaN,IR2,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
15,20,RL,0,10920,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
17,20,RL,0,11241,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
25,20,RL,0,8246,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,20,RL,0,12546,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2007,WD,Normal,182900
1432,120,RL,0,4928,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1442,120,RM,0,4426,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1444,30,RL,0,8854,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1447,20,RL,0,26142,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900

In [15]:
df[df.FireplaceQu.isna()].Fireplaces.unique()

array(['0'], dtype=object)

In [30]:
df.GarageYrBlt = df.GarageYrBlt.replace(np.nan, '3000')

In [31]:
df.GarageYrBlt.unique()

array(['2003', '1976', '2001', '1998', '2000', '1993', '2004', '1973',
       '1931', '1939', '1965', '2005', '1962', '2006', '1960', '1991',
       '1970', '1967', '1958', '1930', '2002', '1968', '2007', '2008',
       '1957', '1920', '1966', '1959', '1995', '1954', '1953', '3000',
       '1983', '1977', '1997', '1985', '1963', '1981', '1964', '1999',
       '1935', '1990', '1945', '1987', '1989', '1915', '1956', '1948',
       '1974', '2009', '1950', '1961', '1921', '1900', '1979', '1951',
       '1969', '1936', '1975', '1971', '1923', '1984', '1926', '1955',
       '1986', '1988', '1916', '1932', '1972', '1918', '1980', '1924',
       '1996', '1940', '1949', '1994', '1910', '1978', '1982', '1992',
       '1925', '1941', '2010', '1927', '1947', '1937', '1942', '1938',
       '1952', '1928', '1922', '1934', '1906', '1914', '1946', '1908',
       '1929', '1933'], dtype=object)

In [33]:
df[df.PoolQC.isna()].PoolArea

1       0
2       0
3       0
4       0
5       0
       ..
1456    0
1457    0
1458    0
1459    0
1460    0
Name: PoolArea, Length: 1453, dtype: object

In [35]:
df[df.MiscFeature.isna()].MiscVal

1       0
2       0
3       0
4       0
5       0
       ..
1455    0
1456    0
1457    0
1459    0
1460    0
Name: MiscVal, Length: 1406, dtype: object

In [36]:
df =df.replace(np.nan, 'NA')

In [37]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,2,2008,WD,Normal,208500
2,20,RL,80,9600,Pave,NA,Reg,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,5,2007,WD,Normal,181500
3,60,RL,68,11250,Pave,NA,IR1,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,9,2008,WD,Normal,223500
4,70,RL,60,9550,Pave,NA,IR1,Lvl,AllPub,Corner,...,0,NA,NA,NA,0,2,2006,WD,Abnorml,140000
5,60,RL,84,14260,Pave,NA,IR1,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62,7917,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,8,2007,WD,Normal,175000
1457,20,RL,85,13175,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,MnPrv,NA,0,2,2010,WD,Normal,210000
1458,70,RL,66,9042,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68,9717,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,4,2010,WD,Normal,142125
1460,20,RL,75,9937,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,6,2008,WD,Normal,147500

In [44]:
df['SalePrice'].describe()

count       1460
unique       663
top       140000
freq          20
Name: SalePrice, dtype: object

# column wich do not need dumies variable